### ISSUE TITLE
how can I do the same things with Debian?

### ISSUE THREAD

**Issue by yap241986** [leifliddy/asahi-fedora-usb#1]
how can I do the same things with Debian?

MacBook Air M1

**Comment by leifliddy** [comment]
Sorry, I'm not really skilled with Debian-based distros. 
However, there are instructions here on how to create an bootable Debian usb drive.
https://git.zerfleddert.de/cgi-bin/gitweb.cgi/m1-debian/

Although, I think the resulting drive is read-only. 

Actually, if you already have Debian installed on an M1 system you should be able to modify these instructions to create a read-write bootable Debian drive. 
https://github.com/AsahiLinux/asahi-installer/issues/71#issuecomment-1094275439
