### ISSUE TITLE
Can I make a 30GB partition on my external SSD and boot instead of USB ?

### ISSUE THREAD

**Issue by krushnadeore** [leifliddy/asahi-fedora-usb#10]
Is there any way to make partition of 30-40GB on external SSD (Samsung T7) and boot to fedora and will it be safe or will cause SSD corruption (using APFS non encry )

**Comment by leifliddy** [comment]
You can create a 30GB root partition by modifying 

https://github.com/leifliddy/asahi-fedora-usb/blob/main/build.sh
and replacing 
```
echo -e 'o\ny\nn\n\n\n+600M\nef00\nn\n\n\n+1G\n8300\nn\n\n\n\n8300\nw\ny\n' | gdisk $usb_device
````
with
```
echo -e 'o\ny\nn\n\n\n+600M\nef00\nn\n\n\n+1G\n8300\nn\n\n\n+30G\n8300\nw\ny\n' | gdisk "$usb_device"
```
