### ISSUE TITLE
Script fails if SELinux is disabled

### ISSUE THREAD

**Issue by div72** [leifliddy/asahi-fedora-usb#23]
Script fails with `setenforce: SELinux is disabled` on the following line if the SELinux is disabled:
https://github.com/leifliddy/asahi-fedora-usb/blob/9b72a67e9f5a545d069dbdf67cf767b003943274/build.sh#L250

Might want to check if it's in the Enforcing state before setting it to Permissive. (`getenforce` works and returns `Disabled`)

**Comment by leifliddy** [comment]
Good point. I should check to see if selinux disabled or not. I'll make that change tonight...

**Comment by leifliddy** [comment]
I just pushed the following commit
https://github.com/leifliddy/asahi-fedora-usb/commit/1f04f2880954f9cc33e5b0329b899d64b0fc7c82

Can you tell me if that works for you?

**Comment by div72** [comment]
Yep, fixed. Thanks.
