### ISSUE TITLE
Do I need to install u-boot first?

### ISSUE THREAD

**Issue by Ran-Xing** [leifliddy/asahi-fedora-usb#27]
I flashed the firmware for the USB flash drive according to the tutorial, but when I plugged it into my Mac and turned it on, no startup items were displayed.

**Comment by leifliddy** [comment]
Do you have Asahi Linux installed on the internal drive?

**Comment by Ran-Xing** [comment]
Asahi Linux is not installed on my internal drive.
I want to install it on a USB flash drive, and I don't have an operating system now.

**Comment by Ran-Xing** [comment]
My Mac Mini hard disk is broken, so I can only start the system on an external hard disk.

**Comment by Ran-Xing** [comment]
@leifliddy I solved the problem after replacing the hard drive. It may be due to aging.
